# backend/schemas/planner.py
"""Pydantic model representing the structured output of the Research Planner.

The planner should return a JSON object that can be parsed into this model.
Fields are chosen to give a concise yet comprehensive research plan.
"""

from pydantic import BaseModel, Field
from typing import List, Optional

class PlannerOutput(BaseModel):
    """Structured research plan generated by the Planner agent."""

    title: str = Field(..., description="A concise title for the research plan.")
    summary: str = Field(..., description="High‑level summary of the research direction.")
    keywords: List[str] = Field(..., description="Key terms or topics to guide literature search.")
    subtopics: List[str] = Field(..., description="Main sub‑areas that should be explored.")
    research_questions: List[str] = Field(..., description="Potential research questions to investigate.")
    methodology_suggestions: List[str] = Field(..., description="Suggested methods or approaches for the research.")
    timeline_weeks: Optional[int] = Field(None, description="Rough timeline (in weeks) for completing the research.")
