# backend/schemas/research.py

"""Pydantic models for research request and response.
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any

class ResearchRequest(BaseModel):
    """Input schema for the /research endpoint."""

    topic: str = Field(..., description="Broad research topic supplied by the user")
    experience_level: str = Field(..., description="User's experience level (e.g., beginner, intermediate, expert)")
    interest: Optional[str] = Field(None, description="Optional specific area of interest")

class ResearchResponse(BaseModel):
    """Response schema for the /research endpoint.

    Includes the structured planner output and discovered papers.
    """

    status: str = Field("pending", description="Overall status of the research workflow")
    details: Optional[Dict[str, Any]] = Field(
        None, description="Optional dictionary with intermediate results or metadata"
    )
    planner_output: Optional[Dict[str, Any]] = Field(
        None, description="Structured research plan generated by the planner"
    )
    papers: Optional[List[Dict[str, Any]]] = Field(
        None, description="Research papers discovered by the Discovery Agent"
    )
